---

# Python 3

- name: Install Python3
  yum: name={{ item }} state=latest
  with_items:
    - python34
    - python34-devel
    - python34-setuptools

- name: Install pip3
  easy_install: name=pip executable=easy_install-3.4
